// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

public class GuestUser {

	public ArrayList<Book> booksList;
	public ArrayList<User> userList;
	
	BookFactory bookFactory = new BookFactory();
	
	public void signUp() {
		System.out.println(">>>>>>LOG: Signin up.");
		
		Scanner in = new Scanner(System.in);
		
		System.out.println("Enter username: ");
		String userName = in.nextLine();
		
		System.out.println("Enter first name: ");
		String firstName = in.nextLine();
		
		System.out.println("Enter last name: ");
		String lastName = in.nextLine();
		
		System.out.println("Enter password: ");
		String password = in.nextLine();
		
		System.out.println("Enter security question: ");
		String securityQuestion = in.nextLine();
		
		System.out.println("Enter answer: ");
		String answer = in.nextLine();
		
		Random id = new Random();
		int low = 1000;
		int high = 11000;
		int userId = id.nextInt(high-low) + low;
		
		User user = new User(userName, userId, firstName, lastName, password, securityQuestion, answer);
		userList.add(user);
		
		System.out.println(">>>>>>LOG: You are now registered user.");
	}

	public void searchBook(String searchKeyword) {
		List<String> searchResult = new ArrayList<String>();

		ArrayList<Book> availableBooksList = booksList;

		for (Book book : availableBooksList) {
			String bookTitle = book.getTitle();
			if (bookTitle.toLowerCase().contains(searchKeyword.toLowerCase())) {
				searchResult.add(bookTitle);
			}
		}

		if (!searchResult.isEmpty()) {
			System.out.println(">>>>>>LOG: Follwoing books found based on your search keyword:");

			for (String bookName : searchResult) {
				System.out.println(bookName);
			}
		} else {
			System.out.println(">>>>>>LOG: No books found based on your search keyword.");
		}
	}

}
