// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.util.Date;
import java.util.concurrent.TimeUnit;

public class LoanedBook {
	
	private Date issueDate;
	private Date returnDate;
	private String alertMessage;
	
	public Date getIssueDate() {
		return issueDate;
	}

	public void setIssueDate(Date issueDate) {
		this.issueDate = issueDate;
	}

	public Date getReturnDate() {
		return returnDate;
	}

	public void setReturnDate(Date returnDate) {
		this.returnDate = returnDate;
	}

	public String getAlertMessage() {
		return alertMessage;
	}

	public void setAlertMessage(String alertMessage) {
		this.alertMessage = alertMessage;
	}

	public int calculateDurationDays() {
		long diff = issueDate.getTime() - returnDate.getTime();
        return (int) TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);
	}
	
	public void alert() {
		System.out.println("ALERT: "+alertMessage);
	}

}
