
// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

import java.util.ArrayList;
import java.util.Scanner;

public class RegisteredUser {

	protected String username;
	protected int Id;
	protected String firstName;
	protected String lastName;
	protected String password;
	protected String securityQuestion;
	protected String answer;

	BookFactory bookFactory = new BookFactory();
	LoanedBook loanedBook = new LoanedBook();
	
	ArrayList<User> userList;
	
	public RegisteredUser(String username, int id, String firstName, String lastName, String password,
			String securityQuestion, String answer) {
		super();
		this.username = username;
		Id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.password = password;
		this.securityQuestion = securityQuestion;
		this.answer = answer;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public int getId() {
		return Id;
	}

	public void setId(int id) {
		Id = id;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSecurityQuestion() {
		return securityQuestion;
	}

	public void setSecurityQuestion(String securityQuestion) {
		this.securityQuestion = securityQuestion;
	}

	public String getAnswer() {
		return answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	public RegisteredUser() {
		super();
	}

	public boolean login(String userName, String passWord, String userType) {

		String typeOfUser = userType.toLowerCase();

		switch (typeOfUser) {
		case "user":
			if (userName.equalsIgnoreCase("user123") && passWord.equalsIgnoreCase("user123")) {
				System.out.println("LOG: You are now logged in as User.");
				return true;
			} else {
				System.out.println("\nInvalid username or password, try again!");
				return false;
			}

		case "admin":
			if (userName.equalsIgnoreCase("admin123") && passWord.equalsIgnoreCase("admin123")) {
				System.out.println("LOG: You are logged in as Admin.");
				return true;
			} else {
				System.out.println("\nInvalid username or password, try again!");
				return false;
			}

		default:
			return false;
		}
	}

	public void logout() {
		System.out.println(">>>>>>LOG: Logging out the system");
		System.exit(0);
	}

	public void forgot() {
		System.out.println("Enter user id to reset the password:");
		Scanner in = new Scanner(System.in);
		int userId = in.nextInt();

		User userToResetPassword = getUserFromId(userId);

		if (userToResetPassword != null) {
			System.out.println(
					"You are going to reset the password for the username: " + userToResetPassword.getUsername());

			System.out.println("Enter new password: ");
			String newPassword = in.nextLine();

			userToResetPassword.setPassword(newPassword);

			System.out.println(
					">>>>>>LOG: New password has been setup for the username: " + userToResetPassword.getUsername());
		}

	}
	
	private User getUserFromId(int userId) {

		User userFromId = null;

		for (User user : userList) {
			if (user.getId() == userId) {
				userFromId = user;
				break;
			}
		}

		if (userFromId == null) {
			System.out.println("ERROR!!! Please enter a valid user id.");
		}

		return userFromId;
	}

}
