// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

public class TextBook extends Book {

	public TextBook() {
		super();
	}

	public TextBook(String title, String type, String author, int nop, int id, boolean onLoan) {
		super(title, type, author, nop, id, onLoan);
	}

	public void displayDetails() {
		System.out.println("Book details");

		System.out.println("Book title: " + title);
		System.out.println("Book type: " + type);
		System.out.println("Book author: " + author);
		System.out.println("Book number of pages: " + nop);
		System.out.println("Book id: " + Id);
	}

}
